export interface LatLon {
  lat: number
  lon: number
}

/** Manual per-crossing time correction (ms, signed), keyed by the crossing's 0-based index in the
 *  array `detectLapCrossings` returns -- see shared/telemetry/laps.ts. Canonical home here (not
 *  laps.ts) since it's persisted in ProjectPayload/the project file schema, same reasoning as
 *  LatLon; laps.ts re-exports it for the call sites that only care about lap detection. */
export type CrossingAdjustments = Record<string, number>

/** Marks a detected crossing (by the same raw detection-order index CrossingAdjustments uses) as a
 *  false lap the user manually deleted -- see shared/telemetry/laps.ts's detectLapCrossings. */
export type CrossingIgnoreSet = Record<string, boolean>

export interface TelemetrySample {
  /** Milliseconds from the start of the video, aligned with HTMLVideoElement.currentTime * 1000 */
  cts: number
  lat: number
  lon: number
  /** Meters */
  altitude: number
  /** Meters per second */
  speed2D: number
  /** Meters per second */
  speed3D: number
}

/** One raw IMU reading (accelerometer, gyroscope, or gravity vector) in the camera's own body-frame
 *  axes -- NOT vehicle-relative. Which raw axis is "vertical"/"lateral"/"longitudinal" depends on the
 *  camera model and mount, and is resolved separately (see shared/telemetry/imuCalibration.ts), not
 *  baked into this type. */
export interface ImuSample {
  cts: number
  x: number
  y: number
  z: number
}

export interface TelemetryData {
  deviceName: string
  gpsStream: 'GPS5' | 'GPS9'
  samples: TelemetrySample[]
  videoDurationMs: number
  /** Accelerometer, m/s^2. Always an array (empty if not present/parsed) -- no null-checks needed downstream. */
  accel: ImuSample[]
  /** Gyroscope, rad/s. Same always-an-array convention as accel. */
  gyro: ImuSample[]
  /** Gravity-direction unit vector -- only present on newer cameras/firmware. Empty when not recorded. */
  gravity: ImuSample[]
}

export interface VideoMeta {
  path: string
  fileName: string
  durationMs: number
  fps: number
  width: number
  height: number
  /** ffprobe codec_name of the video stream, e.g. 'h264', 'hevc'. */
  codec: string
  /** ffprobe pix_fmt of the video stream, e.g. 'yuv420p', 'yuv420p10le'. */
  pixFmt: string
  /** Whether the file has an audio stream at all -- GoPro clips normally do, but export needs to
   *  know before building an audio filter/map graph, and mixed audio/no-audio clips in one
   *  sequence can't be combined cleanly. */
  hasAudio: boolean
  /** Path to this clip's GoPro-written low-res proxy sidecar (e.g. GH010230.MP4 -> GL010230.LRV),
   *  if one sits next to the source file -- null otherwise (not every import has one; it's only
   *  written by the camera itself, never generated by this app). Always a small, fast-start H.264
   *  file regardless of the main clip's own codec, so the live preview can fall back to it instead
   *  of a from-scratch transcode when native playback of the original fails or stalls. Never used
   *  for export, which always reads the original source file. */
  lrvPath: string | null
}

/** One clip in a multi-clip timeline. Clips are always contiguous (GoPro auto-splits one long
 *  recording at ~4GB into parts like GH010230.MP4/GH020230.MP4) -- `startOffsetMs` is this clip's
 *  position in the GLOBAL stitched timeline (cumulative sum of preceding clips' durations). */
export interface ClipInfo {
  video: VideoMeta
  startOffsetMs: number
}

export interface ImportResult {
  /** Ordered, contiguous, always at least 1. */
  clips: ClipInfo[]
  /** Stitched across all clips already -- global `cts`, `videoDurationMs` equal to the sum of
   *  every clip's duration. Every telemetry/lap/sector/widget consumer just uses this directly,
   *  with zero awareness of how many clips it came from. */
  telemetry: TelemetryData
}

export interface WidgetTransform {
  /** Fractions of frame size (0-1), resolution-independent so the same layout works at any export resolution. */
  x: number
  y: number
  w: number
  h: number
  /** Degrees */
  rotation: number
  zIndex: number
  /** When true, blocks drag/resize (and multi-select group-move) for this widget -- for pinning
   *  placement once it's dialed in without it accidentally moving while working on neighbors. */
  locked: boolean
  /** A real OS-installed font family name, `FORMULA1_FONT_ID` (the bundled default look), or `null`
   *  to inherit `ProjectPayload.defaultFontFamily` -- see shared/render/fonts.ts's resolveFontStack,
   *  the single place this is actually resolved to a drawable font stack. */
  fontFamily: string | null
}

export interface GpsTrackWidgetInstance extends WidgetTransform {
  id: string
  type: 'gpsTrack'
  style: import('./render/drawGpsWidget').GpsWidgetStyle
}

export interface SpeedometerAnalogWidgetInstance extends WidgetTransform {
  id: string
  type: 'speedometerAnalog'
  style: import('./render/drawSpeedometer').SpeedometerStyle
}

export interface SpeedometerDigitalWidgetInstance extends WidgetTransform {
  id: string
  type: 'speedometerDigital'
  style: import('./render/drawSpeedometer').SpeedometerStyle
}

export interface TimerWidgetInstance extends WidgetTransform {
  id: string
  type: 'timer'
  style: import('./render/drawTimer').TimerStyle
}

export interface SectorTimerWidgetInstance extends WidgetTransform {
  id: string
  type: 'sectorTimer'
  style: import('./render/drawSectorTimer').SectorTimerStyle
}

export interface DeltaTimeWidgetInstance extends WidgetTransform {
  id: string
  type: 'deltaTime'
  style: import('./render/drawDeltaTime').DeltaTimeStyle
}

export interface PredictiveLapTimerWidgetInstance extends WidgetTransform {
  id: string
  type: 'predictiveLapTimer'
  style: import('./render/drawPredictiveLapTimer').PredictiveLapTimerStyle
}

export interface ApexSpeedCalloutWidgetInstance extends WidgetTransform {
  id: string
  type: 'apexSpeedCallout'
  style: import('./render/drawApexSpeedCallout').ApexSpeedCalloutStyle
}

export interface SpeedDistanceGraphWidgetInstance extends WidgetTransform {
  id: string
  type: 'speedDistanceGraph'
  style: import('./render/drawSpeedDistanceGraph').SpeedDistanceGraphStyle
}

export interface GForceDiagramWidgetInstance extends WidgetTransform {
  id: string
  type: 'gForceDiagram'
  style: import('./render/drawGForceDiagram').GForceDiagramStyle
}

export interface RollAngleWidgetInstance extends WidgetTransform {
  id: string
  type: 'rollAngle'
  style: import('./render/drawRollAngle').RollAngleStyle
}

export interface SessionSummaryWidgetInstance extends WidgetTransform {
  id: string
  type: 'sessionSummary'
  style: import('./render/drawSessionSummary').SessionSummaryStyle
}

export interface LapConsistencyWidgetInstance extends WidgetTransform {
  id: string
  type: 'lapConsistency'
  style: import('./render/drawLapConsistency').LapConsistencyStyle
}

export interface CustomTextWidgetInstance extends WidgetTransform {
  id: string
  type: 'customText'
  style: import('./render/drawCustomText').CustomTextStyle
}

export interface ElevationWidgetInstance extends WidgetTransform {
  id: string
  type: 'elevation'
  style: import('./render/drawElevation').ElevationStyle
}

export interface DistanceWidgetInstance extends WidgetTransform {
  id: string
  type: 'distance'
  style: import('./render/drawDistance').DistanceStyle
}

export interface CompassWidgetInstance extends WidgetTransform {
  id: string
  type: 'compass'
  style: import('./render/drawCompass').CompassStyle
}

export interface AccelTimerWidgetInstance extends WidgetTransform {
  id: string
  type: 'accelTimer'
  style: import('./render/drawAccelTimer').AccelTimerStyle
}

export type WidgetInstance =
  | GpsTrackWidgetInstance
  | SpeedometerAnalogWidgetInstance
  | SpeedometerDigitalWidgetInstance
  | TimerWidgetInstance
  | SectorTimerWidgetInstance
  | DeltaTimeWidgetInstance
  | PredictiveLapTimerWidgetInstance
  | ApexSpeedCalloutWidgetInstance
  | SpeedDistanceGraphWidgetInstance
  | GForceDiagramWidgetInstance
  | RollAngleWidgetInstance
  | SessionSummaryWidgetInstance
  | LapConsistencyWidgetInstance
  | CustomTextWidgetInstance
  | ElevationWidgetInstance
  | DistanceWidgetInstance
  | CompassWidgetInstance
  | AccelTimerWidgetInstance

export interface ProjectPayload {
  imported: ImportResult
  widgets: WidgetInstance[]
  /** One start/finish line shared by every widget that needs lap/sector detection (timer in laps
   *  mode, sectorTimer, and any future widget with the same need) -- set once, used everywhere,
   *  instead of each widget needing its own copy. */
  startFinish: LatLon | null
  /** Start/finish detection radius, meters -- see shared/telemetry/laps.ts's
   *  DEFAULT_THRESHOLD_METERS (that constant is the default when this field is absent, e.g. an
   *  older saved project). Tighten it if the track's own layout passes close to the line at some
   *  OTHER point than the actual line, registering a false lap. */
  startFinishRadiusM: number
  /** Manual per-crossing time corrections (ms, signed), keyed by the crossing's 0-based index in
   *  the array `detectLapCrossings` returns for the current startFinish point -- see
   *  shared/telemetry/laps.ts's CrossingAdjustments. Corrects the local-minimum heuristic
   *  registering a crossing a few frames early/late on a particular lap. Keyed to THIS startFinish
   *  point specifically -- cleared whenever it changes, since a different point recomputes a
   *  different crossings array where the same index may no longer mean the same lap. */
  crossingAdjustmentsMs: CrossingAdjustments
  /** Crossings the user manually deleted (a false lap detection) -- see
   *  shared/telemetry/laps.ts's CrossingIgnoreSet. Keyed the same way, and cleared the same time, as
   *  crossingAdjustmentsMs above. */
  ignoredCrossings: CrossingIgnoreSet
  /** Whole-sequence trim (global ms, spanning all clips) -- cuts dead time from the very start of
   *  the first clip and/or the very end of the last clip. Does NOT affect lap/sector detection
   *  (physically tied to GPS crossings, independent of any later edit decision) -- only changes
   *  what the plain elapsed-mode timer widget displays and what export actually renders. */
  trimStartMs: number
  trimEndMs: number
  /** Project-wide default font -- `FORMULA1_FONT_ID` or a real OS-installed font family name (see
   *  shared/render/fonts.ts). Any widget's own `fontFamily` overrides this when set. */
  defaultFontFamily: string
}

/** One entry in the "recently opened" list on the start screen -- persisted to a file in the app's
 *  userData directory (see main/project/recentProjects.ts), not the project file itself. */
export interface RecentProject {
  path: string
  name: string
  lastOpenedAt: string
}

/** A saved, reusable whole-widget-layout template (positions/sizes/styles for every widget in a
 *  project) -- distinct from the built-in per-widget color StylePreset<T>s in widgets/presets.ts,
 *  which only ever touch one widget's own style, not a project's full arrangement. Persisted to a
 *  file in the app's userData directory (see main/project/layoutPresets.ts), not the project file
 *  itself, since a layout is meant to be reused ACROSS projects. */
export interface WidgetLayoutPreset {
  id: string
  name: string
  createdAt: string
  widgets: WidgetInstance[]
}

export interface ImportProgress {
  phase: 'extracting' | 'parsing'
  fraction: number
  /** Which clip (0-indexed) this progress event is for, out of totalClips -- lets the UI show "Clip 2 of 3…". */
  clipIndex: number
  totalClips: number
}

/** Result of comparing the running app against the latest tagged GitHub release (see
 *  main/app/updateCheck.ts). Null (not this type) when the check couldn't complete at all. */
export interface UpdateCheckResult {
  updateAvailable: boolean
  currentVersion: string
  latestVersion: string
  releaseUrl: string
}

